-- ============================================================
-- GoCost — Phase 5m: นำเข้าโครงสร้างกลุ่มจริงจากไฟล์ P&L ที่ส่งมา
-- (16 กลุ่ม, 86 การจัดสรรรหัสบัญชี รวมรหัส 6120-14 ที่แบ่ง 1/3+2/3)
-- รันหลัง phase5l_group_splits.sql
-- ============================================================

-- 1) สร้างกลุ่มทั้ง 16 กลุ่ม
insert into account_groups (code, name) values ('GRP-01', 'รายได้') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-02', 'ต้นทุนในการขาย') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-03', 'ค่าใช้จ่ายในการขาย/ฝ่ายขาย/PC') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-04', 'ค่าใช้จ่ายในการขาย/ส่งเสริมการขาย') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-05', 'ค่าใช้จ่ายในการขาย/ค่าขนส่ง/เดินทาง') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-06', 'ค่าใช้จ่ายในการขาย/แพลตฟอร์ม') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-07', 'ค่าใช้จ่ายในการบริหาร') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-08', 'สวัสดิการ') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-09', 'ค่าเครื่องเขียน/วัสดุสิ้นเปลือง/ค่าซ่อมแซม') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-10', 'ค่าบริการ/ค่าจ้าง') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-11', 'ค่าเช่า') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-12', 'ค่าสาธารณูปโภค') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-13', 'ค่าเบี้ยประกัน/ธรรมเนียมต่างๆ') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-14', 'อื่นๆ') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-15', 'ค่าดอกเบี้ย') on conflict (code) do nothing;
insert into account_groups (code, name) values ('GRP-16', 'อื่นๆ/ไม่ถือเป็นรายจ่ายจริง') on conflict (code) do nothing;

-- 2) จัดสรรรหัสบัญชีเข้ากลุ่ม (100% ต่อรหัส ยกเว้น 6120-14 ที่แบ่งสัดส่วน)
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '4100-01' and g.code = 'GRP-01' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '4100-05' and g.code = 'GRP-01' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '4200-08' and g.code = 'GRP-01' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '4100-03' and g.code = 'GRP-01' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '4100-04' and g.code = 'GRP-01' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '5130-02' and g.code = 'GRP-01' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '5130-04' and g.code = 'GRP-02' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '5130-06' and g.code = 'GRP-02' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '5130-07' and g.code = 'GRP-02' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '5130-12' and g.code = 'GRP-02' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '5130-08' and g.code = 'GRP-03' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-01' and g.code = 'GRP-03' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6110-03' and g.code = 'GRP-03' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6110-08' and g.code = 'GRP-03' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-26' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-02' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-03' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-04' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-27' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-28' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-29' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-30' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-31' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-14' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-15' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-16' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-13' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-23' and g.code = 'GRP-04' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-05' and g.code = 'GRP-05' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-09' and g.code = 'GRP-05' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-11' and g.code = 'GRP-05' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-12' and g.code = 'GRP-05' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6001-01' and g.code = 'GRP-05' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6001-02' and g.code = 'GRP-05' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6001-03' and g.code = 'GRP-05' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6001-04' and g.code = 'GRP-05' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6130-04' and g.code = 'GRP-05' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-17' and g.code = 'GRP-06' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-19' and g.code = 'GRP-06' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-20' and g.code = 'GRP-06' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-22' and g.code = 'GRP-06' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-24' and g.code = 'GRP-06' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6110-01' and g.code = 'GRP-07' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6110-19' and g.code = 'GRP-07' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6110-02' and g.code = 'GRP-07' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6110-04' and g.code = 'GRP-07' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6110-05' and g.code = 'GRP-07' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6110-09' and g.code = 'GRP-07' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6110-10' and g.code = 'GRP-07' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6100-12' and g.code = 'GRP-08' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6110-17' and g.code = 'GRP-08' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6000-06' and g.code = 'GRP-08' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-01' and g.code = 'GRP-09' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-02' and g.code = 'GRP-09' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-03' and g.code = 'GRP-09' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-08' and g.code = 'GRP-09' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-09' and g.code = 'GRP-09' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-10' and g.code = 'GRP-09' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-12' and g.code = 'GRP-10' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-13' and g.code = 'GRP-10' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-18' and g.code = 'GRP-10' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-15' and g.code = 'GRP-10' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-16' and g.code = 'GRP-11' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6120-17' and g.code = 'GRP-11' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6130-01' and g.code = 'GRP-12' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6130-02' and g.code = 'GRP-12' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6130-03' and g.code = 'GRP-12' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6130-06' and g.code = 'GRP-12' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6130-05' and g.code = 'GRP-13' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6150-04' and g.code = 'GRP-13' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6150-05' and g.code = 'GRP-13' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6160-01' and g.code = 'GRP-13' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6160-02' and g.code = 'GRP-13' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6160-04' and g.code = 'GRP-13' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6160-07' and g.code = 'GRP-13' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6170-04' and g.code = 'GRP-13' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6170-06' and g.code = 'GRP-14' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6170-01' and g.code = 'GRP-15' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6170-09' and g.code = 'GRP-15' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6170-08' and g.code = 'GRP-16' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6190-01' and g.code = 'GRP-16' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6190-02' and g.code = 'GRP-16' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6190-03' and g.code = 'GRP-16' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 1.0 from accounts a, account_groups g where a.code = '6190-04' and g.code = 'GRP-16' on conflict (account_id, group_id) do update set fraction = excluded.fraction;

-- 3) รหัส 6120-14 — แบ่งสัดส่วนตามไฟล์จริง (1/3 ฝ่ายขาย/PC, 2/3 บริหาร)
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 0.3333333333 from accounts a, account_groups g where a.code = '6120-14' and g.code = 'GRP-03' on conflict (account_id, group_id) do update set fraction = excluded.fraction;
insert into account_group_splits (account_id, group_id, fraction) select a.id, g.id, 0.6666666667 from accounts a, account_groups g where a.code = '6120-14' and g.code = 'GRP-07' on conflict (account_id, group_id) do update set fraction = excluded.fraction;